---
title: "homework-3"
date: 05-22-2025
author: Mariko Bronson
format: html
---

https://github.com/MarikoBron/ENVS-193DS_homework-03.git

```{r packages and data}
#install packages
library(tidyverse)
library(here)
library(janitor)
library(flextable)
library(readxl)
library(ggplot2)
library(colorspace)

#create object screentime
screentime <- read_xlsx(
  here("data", "193DS_screentime_updated.xlsx"),
  sheet = "Sheet1")
```

#Problem 1: Personal Data

## a. Data Summarizing

I am adding together five quantitative variables to calculate my perceived daily stress level, including the number of classes skipped, number of assignments/tasks due, number of assignments/tasks done, number of plans cancelled, and number of hours slept. I am comparing this daily self-imposed stress value to my daily screentime to look for correlations between the two values because sometimes I feel like high perceived stress pushes me to use my phone more to avoid tasks.

## b. Visualization

```{creating a visualization}

screentime_clean <- screentime |>  #create object screentime_clean
  clean_names() |> 
  select(number_classes_skipped, number_tasks_due, number_hw_assn_done_1, number_plans_cancelled, x8_number_hrs_slept, stress_value, screen_time_h) |> 
  rename( 
        `classes skipped` = number_classes_skipped ,
        `tasks due` = number_tasks_due,
        `assignments completed` = number_hw_assn_done_1,
        `plans cancelled` = number_plans_cancelled,
        `hours slept` = x8_number_hrs_slept,
        `stress value` = stress_value,
        `screentime(h)` = screen_time_h #renaming all of my columns
         )

screentime_clean$`tasks due`[21] <- 1 #fixing a value i entered in wrong

hcl_palettes() #downloading cute color palette just in case I need it
hcl_palettes(plot = TRUE)

ggplot(screentime_clean, 
       aes(
         x = `stress value`,
         y = `screentime(h)`,
         color = factor(`tasks due`)
       )) + #create scatterplot to look for correlation between stress value and screentime (there is lowkey none)
  geom_point(
    fill = "honeydew", 
    shape = 23,
    alpha = 0.6,
    size = 3.5,
    stroke = 3 #make scatterplot cute
  ) +
  
  labs(
    title = "Relationship Between Screentime, Perceived Stress Value,\nand Number of Tasks Due- Screentime increases as \nTasks Decrease",
    x = "Stress Value",
    y = "Screentime (h)",
    color = "Tasks Due"
  ) +
  
  scale_color_discrete_sequential(palette = "SunsetDark")


```

## c. Caption

There is no obvious correlation between daily perceived stress value and daily hours of screentime,but there is a correlation between number of tasks due and daily screentime. The highest daily screentime values are on days with zero tasks due, and days with more tasks due appear to have lower screentime. Perceived stress value is calculated by adding up point values for the daily number of classes skipped, tasks due, plans cancelled, and a point is also added for every hour of sleep that is less than eight. Points are subtracted for every task completed and for every hour of sleep that exceeds eight.

# Problem 3

## a.